# Generated by Django 2.2.9 on 2020-02-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapi', '0002_auto_20200226_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userratesprofessor',
            name='module_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapi.ProfessorTeachesModule'),
        ),
    ]
