# Generated by Django 2.2.9 on 2020-03-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapi', '0003_auto_20200226_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='professors',
        ),
    ]
