# Generated by Django 2.2.9 on 2020-03-06 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapi', '0004_remove_module_professors'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='prof_cod',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
