# Generated by Django 2.2.9 on 2020-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapi', '0005_professor_prof_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_cod',
            field=models.CharField(default='n/a', max_length=10, unique=True),
        ),
    ]
